<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	
		// Se referencia la capa de negocio para que se conozca el IServicioCredito,SolicitudCredito,ResultadoCredito
		//Tambien se marca la capa de acceso de datos para poder implementar de manera real el IaccesoCentralRiesgo
		
  <ItemGroup>
    <ProjectReference Include="..\CapaAccesoDatos\CapaAccesoDatos.csproj" />
    <ProjectReference Include="..\CapaNegocio\CapaNegocio.csproj" />
  </ItemGroup>

</Project>